#[[main]]
#  name = "Aktuelles"
#  pageRef = "aktuelles/"
#  weight = 1

[[main]]
  name = "Einsätze"
  pageRef = "einsaetze/"
  weight = 10

[[main]]
  name = "Förderverein"
  pageRef = "foerderverein/"
  weight = 30

[[main]]
  name = "Über uns"
  weight = 40

[[main]]
  name = "Feuerwehrhaus"
  parent = "Über uns"
  pageRef = "feuerwehrhaus/"
  weight = 1

[[main]]
  name = "Fahrzeuge"
  parent = "Über uns"
  pageRef = "fahrzeuge/"
  weight = 10

[[main]]
  name = "Ehemalige Fahrzeuge"
  parent = "Über uns"
  pageRef = "ehemalige/"
  weight = 20

#[[main]]
#  name = "Aufgaben"
#  parent = "Über uns"
#  pageRef = "aufgaben/"
#  weight = 30

[[main]]
  name = "Mitmachen"
  parent = "Über uns"
  pageRef = "mitmachen/"
  weight = 40

[[main]]
  name = "Kontakt"
  parent = "Über uns"
  pageRef = "kontakt/"
  weight = 50

#[[main]]
#  name = "Tags"
#  pageRef = "/tags"
#  weight = 20

[[social]]
  name = "Facebook"
  pre = "fab facebook"
  url = "https://www.facebook.com/feuerwehrhamburgeppendorf"
  weight = 1

[[social]]
  name = "Instagram"
  pre = "fab instagram"
  url = "https://www.instagram.com/feuerwehrhamburgeppendorf/"
  weight = 10

[[social]]
  name = "Twitter"
  pre = "fab x-twitter"
  url = "https://twitter.com/FFEppendorf/"
  weight = 20

[[footer]]
  name = "Links"
  weight = 10

[[footer]]
  parent = "Links"
  name = "Impressum"
  pageRef = "impressum"
  weight = 1

[[footer]]
  parent = "Links"
  name = "Datenschutz"
  pageRef = "datenschutz"
  weight = 2

[[footer]]
  parent = "Links"
  name = "Kontakt"
  pageRef = ""
  weight = 3